// https://github.com/fabian-hiller/valibot/blob/e72faa35cf8356f91c73544ebeadcaf0f7321d5c/library/src/actions/email/email.test.ts

export const validEmailsFromValibot = [
  'email@example.com',
  'a@b.cd',
  '_email@example.com',
  '-email@example.com',
  '+email@example.com',
  'email_@example.com',
  'email-@example.com',
  'email+@example.com',
  'firstname.lastname@example.com',
  'firstname_lastname@example.com',
  'firstname-lastname@example.com',
  'firstname+lastname@example.com',
  '1234567890@example.com',
  '_______@example.com',
  'email@example-domain.com',
  'email@subdomain.example.com',
  'email@subdomain.example-domain.com',
  'email@example.technology',
  'email@example.co.uk',
  'email@subdomain.example.co.uk',
  'email@123.com',
]

export const invalidEmailsFromValibot = [
  ' email@example.com',
  'e mail@example.com',
  'email @example.com',
  'email@ example.com',
  'email@exa mple.com',
  'email@example. com',
  'email@example.com ',
  '@example.com',
  'example.com',
  'email.example.com',
  'email@',
  'email@.com',
  'email@example',
  'email..email@example.com',
  'email@@example.com',
  'email@example..com',
  '.email@example.com',
  'email.@example.com',
  'email@_example.com',
  'email@-example.com',
  'email@+example.com',
  'email@.example.com',
  'email@example_.com',
  'email@example-.com',
  'email@example+.com',
  'email@example.123',
  'email@example.a',
  'email@example@example.com',
  '#$&%@example.com',
  'email@#$&%.com',
  'email@example.#$&%',
  'あいうえお@example.com',
  'email@あいうえお.com',
  'email@example.あいう',
  'Joe Smith <email@example.com>',
  'email@example.com (Joe Smith)',
]
